Change data model restaurant to location
mapshare/mobile-app-backend pull request #12
Opened 2019-09-16 22:34 UTC by kc-leung

fix #8 

- Created Data Model called location and locationImage

I have decided to make a new schema for locationImage for a better performance

2019-09-17 20:47 UTC, coreyjjames requested changes
Looks good just comparing with the UML and we had a few more fields then you have here.

1)  "OptionalInformation" field, which I am thinking would be a place to hold optional notes about the location. We can change the name to something like "locationNotes" if you want.

2) "categoyId" field, which will store the id for the type Category.

3)  "locationMark" field, which will store the id for the type Mark. (Note: UML says its a Set of marks but that I think is wrong a location would only save one mark.

2019-09-17 21:39 UTC, kc-leung commented
> 
> 
> Looks good just comparing with the UML and we had a few more fields then you have here.
> 
>     1. "OptionalInformation" field, which I am thinking would be a place to hold optional notes about the location. We can change the name to something like "locationNotes" if you want.
> 
>     2. "categoyId" field, which will store the id for the type Category.
> 
>     3. "locationMark" field, which will store the id for the type Mark. (Note: UML says its a Set of marks but that I think is wrong a location would only save one mark.

Will add OptionalInformation as AdditionalInformation and locationMarkSet. Also, I was thinking to bring up in the coming meeting changing category relation to mark instead of location. You can just think about the reason of why and why not of that suggestion and we can discuss on thursday

2019-09-17 22:33 UTC, coreyjjames requested changes
Ya we can leave out categories for now and talk about it in the meeting

2019-09-17 22:33 UTC, coreyjjames commented on models/location.js
> +  groupId: {
UML relates location to Mark, not Group. Then the group will end up relating to Mark.

2019-09-18 02:58 UTC, kc-leung commented
> 
> 
> Ya we can leave out categories for now and talk about it in the meeting

I am leaving the groupID since it is there previously I need to test it first with the routes and services so I can know the reason of having it or not

2019-09-19 02:45 UTC, coreyjjames approved these changes

2019-09-24 21:26 UTC, merged