Add Group Feed and Post Routes
mapshare/mobile-app-backend pull request #13
Opened 2019-09-17 01:43 UTC by coreyjjames

fix #5 fix #4

And I fixed removed code related to price range and cuisines

2019-09-17 12:24 UTC, kc-leung requested changes
@coreyjjames lets keep the routes/dataServices out for the moment in another pull request. This make the PR too large and hard to review. Please just stick to the issue scope which is data model If you want to do the route please create another issue or notify me on Discord so I will create it.

2019-09-17 14:15 UTC, coreyjjames commented
@kc-leung ok I will do that in the future can you approve this PR

2019-09-17 14:28 UTC, kc-leung commented
> 
> 
> @kc-leung ok I will do that in the future can you approve this PR

Will do once I get home

2019-09-18 03:00 UTC, kc-leung approved these changes

2019-09-18 03:02 UTC, merged